version: '3.9'
services:
  db:
    image: postgres:16-alpine
    container_name: bahtapelikanoff_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bahtapelikanoff
    ports:
      - '5434:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
