version: '3.9'

services:
  # Export host metrics (CPU, RAM, FS)
  node_exporter:
    image: prom/node-exporter:v1.8.1
    container_name: pelican_node_exporter
    restart: unless-stopped
    network_mode: "host"   # so that host metrics are visible
    pid: "host"
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro

  # Export PostgreSQL metrics
  postgres_exporter:
    image: quay.io/prometheuscommunity/postgres-exporter:v0.15.0
    container_name: pelican_postgres_exporter
    restart: unless-stopped
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:postgres@db:5432/pelicanbay?sslmode=disable"
    depends_on:
      - db
    ports:
      - "9187:9187"

  # HTTP/TCP probe exporter
  blackbox_exporter:
    image: prom/blackbox-exporter:v0.25.0
    container_name: pelican_blackbox_exporter
    restart: unless-stopped
    ports:
      - '9115:9115'

  # Prometheus server
  prometheus:
    image: prom/prometheus:v2.52.0
    container_name: pelican_prometheus
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    volumes:
      - './monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro'
      - './monitoring/alerts:/etc/prometheus/alerts:ro'
      - prometheus_data:/prometheus
    ports:
      - '9090:9090'
    depends_on:
      - node_exporter
      - postgres_exporter

  # Loki log storage
  loki:
    image: grafana/loki:3.0.0
    container_name: pelican_loki
    restart: unless-stopped
    ports:
      - '3100:3100'

  # Grafana dashboards
  grafana:
    image: grafana/grafana:11.0.0
    container_name: pelican_grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources:ro
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - './monitoring/grafana/json:/var/lib/grafana/dashboards:ro'

    ports:
      - '3001:3000'
    depends_on:
      - prometheus
      - loki

volumes:
  prometheus_data:
  grafana_data:
