global:
  scrape_interval: 15s
  evaluation_interval: 30s

rule_files:
  - 'alerts/*.yml'
  
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node (host) metrics
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']

  # PostgreSQL metrics
  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres_exporter:9187']

  # Application health (blackbox HTTP probe)
  - job_name: 'pelican_healthz'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://host.docker.internal:3000/api/healthz
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115
